#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BuenRide.Resource", IsApplication=true)]

namespace BuenRide
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::BuenRide.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int cameraBearing = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLat = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTargetLng = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraTilt = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cameraZoom = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int mapType = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int uiCompass = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiRotateGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiScrollGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiTiltGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomControls = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int uiZoomGestures = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int useViewLifecycle = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int zOrderOnTop = 2130771984;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000e
			public const int br_cian = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int br_gray = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f04000f
			public const int common_signin_btn_text_dark = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int common_signin_btn_text_light = 2130968592;
			
			// aapt resource value: 0x7f04000c
			public const int light_gray = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int red = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int yellow = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int activity_horizontal_margin = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int activity_vertical_margin = 2131230721;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int fb_login = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_contact_picture = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_launcher = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_plusone_medium_off_client = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_plusone_small_off_client = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_plusone_standard_off_client = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_plusone_tall_off_client = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Icon = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int logo = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int monoandroidsplash = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05005c
			public const int Facebook = 2131034204;
			
			// aapt resource value: 0x7f050041
			public const int RectangleAddReview = 2131034177;
			
			// aapt resource value: 0x7f05000e
			public const int RectangleAddRide = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int RectangleAddStop = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int RectangleByMap = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int RectangleByMap2 = 2131034131;
			
			// aapt resource value: 0x7f050018
			public const int RectangleCalculate = 2131034136;
			
			// aapt resource value: 0x7f050035
			public const int RectangleCalculateCost = 2131034165;
			
			// aapt resource value: 0x7f050010
			public const int RectangleCancelAddRide = 2131034128;
			
			// aapt resource value: 0x7f050050
			public const int RectangleCancelSignUp = 2131034192;
			
			// aapt resource value: 0x7f050006
			public const int RectangleCurrentLocation = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int RectangleCurrentLocation2 = 2131034130;
			
			// aapt resource value: 0x7f050026
			public const int RectangleLogin = 2131034150;
			
			// aapt resource value: 0x7f050029
			public const int RectangleLogin2 = 2131034153;
			
			// aapt resource value: 0x7f05004b
			public const int RectangleLogin3 = 2131034187;
			
			// aapt resource value: 0x7f05004d
			public const int RectangleLogin4 = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int RectangleLogin5 = 2131034190;
			
			// aapt resource value: 0x7f050039
			public const int RectangleLogout = 2131034169;
			
			// aapt resource value: 0x7f05000a
			public const int RectangleObservations = 2131034122;
			
			// aapt resource value: 0x7f050034
			public const int RectangleProfile = 2131034164;
			
			// aapt resource value: 0x7f050031
			public const int RectangleSearchRide = 2131034161;
			
			// aapt resource value: 0x7f050015
			public const int RectangleSeekBarProfite = 2131034133;
			
			// aapt resource value: 0x7f050037
			public const int RectangleShare = 2131034167;
			
			// aapt resource value: 0x7f050046
			public const int RectangleShareFacebook = 2131034182;
			
			// aapt resource value: 0x7f050048
			public const int RectangleShareTwitter = 2131034184;
			
			// aapt resource value: 0x7f05002d
			public const int RectangleSignUp = 2131034157;
			
			// aapt resource value: 0x7f050043
			public const int RectangleViewRides = 2131034179;
			
			// aapt resource value: 0x7f05005d
			public const int Twitter = 2131034205;
			
			// aapt resource value: 0x7f050054
			public const int comentario = 2131034196;
			
			// aapt resource value: 0x7f050023
			public const int containerLogin = 2131034147;
			
			// aapt resource value: 0x7f050027
			public const int email = 2131034151;
			
			// aapt resource value: 0x7f050057
			public const int end_point = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int end_point_value = 2131034200;
			
			// aapt resource value: 0x7f050004
			public const int hybrid = 2131034116;
			
			// aapt resource value: 0x7f050024
			public const int imageView1 = 2131034148;
			
			// aapt resource value: 0x7f05002f
			public const int imageViewFbLogin = 2131034159;
			
			// aapt resource value: 0x7f050052
			public const int image_user = 2131034194;
			
			// aapt resource value: 0x7f050030
			public const int imagelogo = 2131034160;
			
			// aapt resource value: 0x7f05005e
			public const int linearLayout1 = 2131034206;
			
			// aapt resource value: 0x7f050045
			public const int listComments = 2131034181;
			
			// aapt resource value: 0x7f050022
			public const int listRides = 2131034146;
			
			// aapt resource value: 0x7f05002b
			public const int login = 2131034155;
			
			// aapt resource value: 0x7f05005b
			public const int login_shape = 2131034203;
			
			// aapt resource value: 0x7f05004a
			public const int name = 2131034186;
			
			// aapt resource value: 0x7f050000
			public const int none = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int normal = 2131034113;
			
			// aapt resource value: 0x7f050059
			public const int num_stops = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int num_stops_value = 2131034202;
			
			// aapt resource value: 0x7f050014
			public const int numberPickerDays = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int numberPickerGass = 2131034135;
			
			// aapt resource value: 0x7f05000b
			public const int observations = 2131034123;
			
			// aapt resource value: 0x7f05002a
			public const int password = 2131034154;
			
			// aapt resource value: 0x7f05003f
			public const int ratingBar1 = 2131034175;
			
			// aapt resource value: 0x7f050002
			public const int satellite = 2131034114;
			
			// aapt resource value: 0x7f050016
			public const int seekBarProfite = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int signup_form = 2131034117;
			
			// aapt resource value: 0x7f050055
			public const int start_point = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int start_point_value = 2131034198;
			
			// aapt resource value: 0x7f05004f
			public const int telephone = 2131034191;
			
			// aapt resource value: 0x7f050003
			public const int terrain = 2131034115;
			
			// aapt resource value: 0x7f050020
			public const int textView1 = 2131034144;
			
			// aapt resource value: 0x7f050040
			public const int textView_Review = 2131034176;
			
			// aapt resource value: 0x7f050042
			public const int textView_addReview = 2131034178;
			
			// aapt resource value: 0x7f05000f
			public const int textView_addRide = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int textView_addStop = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int textView_byMap = 2131034121;
			
			// aapt resource value: 0x7f05001e
			public const int textView_calcDay = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int textView_calcDayValue = 2131034143;
			
			// aapt resource value: 0x7f05001a
			public const int textView_calcMonth = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int textView_calcMonthValue = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int textView_calcWeek = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int textView_calcWeekValue = 2131034141;
			
			// aapt resource value: 0x7f050019
			public const int textView_calculate = 2131034137;
			
			// aapt resource value: 0x7f050036
			public const int textView_calculateCost = 2131034166;
			
			// aapt resource value: 0x7f050011
			public const int textView_cancelAddRide = 2131034129;
			
			// aapt resource value: 0x7f050051
			public const int textView_cancelSU = 2131034193;
			
			// aapt resource value: 0x7f050007
			public const int textView_currentLocation = 2131034119;
			
			// aapt resource value: 0x7f050025
			public const int textView_emailAddress = 2131034149;
			
			// aapt resource value: 0x7f05003c
			public const int textView_exampleMail = 2131034172;
			
			// aapt resource value: 0x7f05003e
			public const int textView_examplePhone = 2131034174;
			
			// aapt resource value: 0x7f05002c
			public const int textView_login = 2131034156;
			
			// aapt resource value: 0x7f05003a
			public const int textView_logout = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int textView_mail = 2131034171;
			
			// aapt resource value: 0x7f050028
			public const int textView_password = 2131034152;
			
			// aapt resource value: 0x7f05003d
			public const int textView_phone = 2131034173;
			
			// aapt resource value: 0x7f050033
			public const int textView_profile = 2131034163;
			
			// aapt resource value: 0x7f050021
			public const int textView_rides = 2131034145;
			
			// aapt resource value: 0x7f050032
			public const int textView_searchRide = 2131034162;
			
			// aapt resource value: 0x7f050038
			public const int textView_share = 2131034168;
			
			// aapt resource value: 0x7f050047
			public const int textView_share_facebook = 2131034183;
			
			// aapt resource value: 0x7f050049
			public const int textView_share_twitter = 2131034185;
			
			// aapt resource value: 0x7f05002e
			public const int textView_signUp = 2131034158;
			
			// aapt resource value: 0x7f050044
			public const int textView_viewRides = 2131034180;
			
			// aapt resource value: 0x7f050053
			public const int user_name = 2131034195;
			
			// aapt resource value: 0x7f05004c
			public const int username = 2131034188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_add_ride = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_calculate_cost_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_calculate_main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_gps = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_list_rides = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_profile = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int activity_search_ride = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int activity_share = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int activity_sign_up = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int background_image_gradient = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int item_comment = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int item_ride = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int rectangle = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int rectangle_input = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int rectangle_input_gray = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int rectangle_stop = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ShareLayout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ShowMap = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060023
			public const int action_forgot_password = 2131099683;
			
			// aapt resource value: 0x7f060021
			public const int action_log_in = 2131099681;
			
			// aapt resource value: 0x7f06001d
			public const int action_settings = 2131099677;
			
			// aapt resource value: 0x7f060022
			public const int action_sign_up = 2131099682;
			
			// aapt resource value: 0x7f060015
			public const int auth_client_needs_enabling_title = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int auth_client_needs_installation_title = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int auth_client_needs_update_title = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int auth_client_play_services_err_notification_msg = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int auth_client_requested_by_msg = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int auth_client_using_bad_version_title = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_button = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_text = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_enable_title = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_text_phone = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_tablet = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_install_title = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_invalid_account_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_invalid_account_title = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_network_error_text = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_network_error_title = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_unknown_issue = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_unsupported_date_text = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_unsupported_text = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_unsupported_title = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_update_button = 2131099665;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_text = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_update_title = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int common_signin_button_text = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int common_signin_button_text_long = 2131099667;
			
			// aapt resource value: 0x7f060028
			public const int error_field_required = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int error_incorrect_password = 2131099687;
			
			// aapt resource value: 0x7f060025
			public const int error_invalid_email = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int error_invalid_password = 2131099686;
			
			// aapt resource value: 0x7f06001c
			public const int hello = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int hello_world = 2131099678;
			
			// aapt resource value: 0x7f06001b
			public const int library_name = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int location_client_powered_by_google = 2131099674;
			
			// aapt resource value: 0x7f060024
			public const int login_progress_signing_in = 2131099684;
			
			// aapt resource value: 0x7f060029
			public const int password = 2131099689;
			
			// aapt resource value: 0x7f06001f
			public const int prompt_email = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int prompt_password = 2131099680;
			
			// aapt resource value: 0x7f06002b
			public const int title_activity_activity_profile = 2131099691;
			
			// aapt resource value: 0x7f060031
			public const int title_activity_add_review = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int title_activity_add_ride = 2131099698;
			
			// aapt resource value: 0x7f06002f
			public const int title_activity_calculate_cost_main = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int title_activity_list_rides = 2131099696;
			
			// aapt resource value: 0x7f06002a
			public const int title_activity_login = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int title_activity_menu = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int title_activity_search_ride = 2131099694;
			
			// aapt resource value: 0x7f06002c
			public const int title_activity_sign_up = 2131099692;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int Mono_Android_Theme_Splash = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] MapAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
