# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8227a93ed595d37aee64d8ad6b9253b25ec1974d65117effd5e54b435a7fff6333ee754c3ca4175cb8536d186ad94ce6d1f3b694a19d9165c863b0fa4e556da2

test:
  secret_key_base: aa0b1bf3d3bc42285635bfb11c0dc34cc0150d032ed6c482654cc0e28449717f4dcff1a25b3455c3fe3b03045ad59e24278bbd6a3d520a2fc627d8beebc61bd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
